on: 
  workflow_dispatch:

name: rust mipsel build

jobs:

  mipsel:
    name: mipsel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trojan-r
        uses: actions/checkout@v2
        
#      - name: Checkout ring
#        uses: actions/checkout@v2
#        with:
#          repository: 'briansmith/ring'
#          path: './ring'

      - name: Checkout ring PR 1181 with mips support
        run: |
          git clone https://github.com/briansmith/ring.git
          cd ring
          git checkout 9cc0d45f4d8521f467bb3a621e74b1535e118188
          git fetch origin pull/1181/head:mips
          git config --global user.email "example.com"
          git config --global user.name "zrah"
          git merge mips --no-commit --no-ff --allow-unrelated-histories 
      
      - name: Patch Cargo.toml
        run: |
          echo '[patch.crates-io]' >> Cargo.toml
          echo 'ring = { path = "./ring" }' >> Cargo.toml

      #- uses: P3TERX/ssh2actions@v1.0.0
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: mipsel-unknown-linux-musl
          override: true
    
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target mipsel-unknown-linux-musl

      - uses: actions/upload-artifact@v2
        with:
           name: mips-trojan-r
           path: target/mipsel-unknown-linux-musl/release/trojan-r
